services:
  server:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb+srv://abrahamdene:gMkmMLx2Cu4WDSk9@clustereventbridge.ytjwi.mongodb.net/?retryWrites=true&w=majority&appName=ClusterEventbridge
    depends_on:
      - mongo

  frontend:
    build:
      context: ./eventbridge
    ports:
      - "5173:5173"

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
