# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-planning-platform-backend
  namespace: default
spec:
  replicas: 2  # Increased replicas for scalability
  selector:
    matchLabels:
      app: event-planning-platform-backend
  template:
    metadata:
      labels:
        app: event-planning-platform-backend
    spec:
      containers:
        - name: backend-container
          image: dene009/event-planning-platform-backend:latest  # Replace with your backend Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 5001  # Backend application port
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5001"
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: ClusterIP  # Internal service for backend
  selector:
    app: event-planning-platform-backend
  ports:
    - port: 5001
      targetPort: 5001
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-planning-platform-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-planning-platform-frontend
  template:
    metadata:
      labels:
        app: event-planning-platform-frontend
    spec:
      containers:
        - name: frontend-container
          image: dene009/event-planning-platform-frontend:latest  # Replace with your frontend Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 5173  # Frontend application port
          env:
            - name: NODE_ENV
              value: "production"
            - name: VITE_BACKEND_URL
              value: "http://backend-service.default.svc.cluster.local:5001"  # Internal backend URL
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort  # Expose frontend externally
  selector:
    app: event-planning-platform-frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173  # NodePort for external access (ensure it's open on your cluster nodes)

